# Email spam detection

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\ADMIN\\ML-2'

In [5]:
os.chdir("D:\SUSHMITHA\Dataframes_csvFiles")

In [6]:
os.getcwd()

'D:\\SUSHMITHA\\Dataframes_csvFiles'

In [7]:
df=pd.read_csv('spam.csv')

In [8]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.shape

(5572, 2)

In [10]:
len(df)

5572

In [11]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [12]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [13]:
df.columns.tolist()

['Category', 'Message']

In [14]:
df.dtypes

Category    object
Message     object
dtype: object

In [15]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [16]:
df.groupby('Category')

In [39]:
#get the count of spam and ham mails
df.groupby('Category').count()

Message  spam
Category               
ham          4825  4825
spam          747   747

In [18]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [19]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [20]:
df.head(10)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

In [40]:
#splitting of dataset into training and testing dataset
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2,random_state=1)

In [23]:
X_train

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
157                           I'm leaving my house now...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: Message, Length: 4457, dtype: object

In [24]:
X_train.shape

(4457,)

In [25]:
y_train

1642    0
2899    0
480     0
3485    0
157     0
       ..
905     0
5192    0
3980    0
235     1
5157    0
Name: spam, Length: 4457, dtype: int64

In [26]:
y_train.shape

(4457,)

In [27]:
X_test

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
324     That would be great. We'll be at the Guild. Co...
1163    Free entry in 2 a wkly comp to win FA Cup fina...
86      For real when u getting on yo? I only need 2 m...
4214                     I attended but nothing is there.
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
Name: Message, Length: 1115, dtype: object

In [28]:
X_test.shape

(1115,)

In [29]:
y_test

1078    0
4028    0
958     0
4642    0
4674    0
       ..
324     0
1163    1
86      0
4214    0
90      0
Name: spam, Length: 1115, dtype: int64

In [30]:
y_test.shape

(1115,)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [34]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.989237668161435

using sklearn pipeline

In [35]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [36]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [37]:
clf.score(X_test,y_test)

0.989237668161435

In [38]:
clf.predict(emails)

array([0, 1], dtype=int64)